import type { SpecialtyConfig } from "./types";

export const aestheticConfig: SpecialtyConfig = {
  code: "aesthetic",
  nameAr: "تجميل",
  nameEn: "Aesthetic Medicine",
  encounterSections: [
    { id: "chief_complaint", labelAr: "هدف الزيارة التجميلي", labelEn: "Aesthetic concern", kind: "text", required: true, placeholderAr: "تجاعيد الجبهة، تحديد الشفاه، نضارة، ليزر..." },
    { id: "procedure_type", labelAr: "نوع الخدمة", labelEn: "Service type", kind: "select", required: true, options: ["Consultation", "Botulinum toxin", "Dermal filler", "Skin booster", "PRP", "Mesotherapy", "Laser hair removal", "Laser resurfacing", "Chemical peel", "Threads", "Body contouring", "Follow-up"] },
    { id: "treatment_area", labelAr: "منطقة العلاج", labelEn: "Treatment area", kind: "select", options: ["الجبهة", "بين الحاجبين", "حول العين", "تحت العين", "الخدود", "الأنف", "الطيات الأنفية الشفوية", "الشفة العليا", "الشفة السفلى", "الذقن", "زاوية الفك", "الرقبة", "الإبط", "الذراع", "الساق", "الظهر", "البطن", "أخرى"] },
    { id: "fitzpatrick", labelAr: "نوع البشرة Fitzpatrick", labelEn: "Fitzpatrick skin type", kind: "select", options: ["Type I", "Type II", "Type III", "Type IV", "Type V", "Type VI"] },
    { id: "contraindications", labelAr: "موانع أو تحذيرات قبل الإجراء", labelEn: "Contraindications", kind: "textarea", placeholderAr: "حمل/رضاعة، حساسية، أدوية سيولة، التهاب نشط، هربس، كدمات..." },
    { id: "product_used", labelAr: "المنتج / الجهاز المستخدم", labelEn: "Product or device", kind: "text", placeholderAr: "Brand + concentration أو اسم الجهاز والعدسة" },
    { id: "batch_number", labelAr: "Batch / Lot", labelEn: "Batch / lot number", kind: "text", placeholderAr: "رقم التشغيلة" },
    { id: "expiry_date", labelAr: "تاريخ انتهاء المنتج", labelEn: "Expiry date", kind: "date" },
    { id: "quantity", labelAr: "الكمية أو الجرعة", labelEn: "Quantity or dose", kind: "text", placeholderAr: "مثال: 0.6 ml، 24 units، fluence 18J" },
    { id: "technique_depth", labelAr: "التقنية / العمق", labelEn: "Technique / depth", kind: "text", placeholderAr: "Intradermal, subcutaneous, linear threading, bolus..." },
    { id: "anesthesia", labelAr: "التخدير أو التحضير", labelEn: "Anesthesia / prep", kind: "text", placeholderAr: "Topical lidocaine، ice، chlorhexidine..." },
    { id: "before_photos", labelAr: "صور قبل الإجراء", labelEn: "Before photos", kind: "select", options: ["تم التقاطها", "لم تُلتقط", "المراجع رفض"] },
    { id: "consent", labelAr: "الموافقة المستنيرة", labelEn: "Informed consent", kind: "select", required: true, options: ["تم شرح الفوائد والمخاطر ووقّع", "تم الشرح بانتظار التوقيع", "استشارة فقط"] },
    { id: "adverse_events", labelAr: "مضاعفات أثناء الإجراء", labelEn: "Adverse events", kind: "textarea", placeholderAr: "لا توجد، ألم، نزف بسيط، كدمة، تفاعل وعائي..." },
    { id: "aftercare", labelAr: "تعليمات ما بعد الإجراء", labelEn: "Aftercare", kind: "textarea", placeholderAr: "تجنب الحرارة والرياضة والمساج، واقي شمس، كمادات..." },
    { id: "review_plan", labelAr: "خطة المراجعة / الجلسة القادمة", labelEn: "Review plan", kind: "textarea", placeholderAr: "مراجعة خلال أسبوعين، جلسة بعد 4 أسابيع، صور بعد..." },
  ],
  documentTypes: [
    { id: "prescription", labelAr: "وصفة طبية", labelEn: "Prescription" },
    { id: "procedure_consent", labelAr: "موافقة مستنيرة للإجراء", labelEn: "Informed consent" },
    { id: "before_after_report", labelAr: "تقرير قبل/بعد", labelEn: "Before/after report" },
    { id: "procedure_note", labelAr: "ملخص الإجراء", labelEn: "Procedure note" },
    { id: "aftercare_sheet", labelAr: "تعليمات ما بعد الإجراء", labelEn: "Aftercare sheet" },
  ],
  quickDiagnoses: [
    "Dynamic wrinkles - botulinum toxin",
    "Lip augmentation - dermal filler",
    "Midface volume loss",
    "Tear trough correction",
    "Laser hair reduction",
    "Skin rejuvenation",
    "Acne scar treatment",
    "Post-procedure follow-up",
  ],
  favoriteMedications: [
    "Sunscreen SPF 50 daily",
    "Cold compress 10 minutes as needed",
    "Avoid heat, massage, sauna, and exercise for 24-48h",
    "Gentle cleanser twice daily",
    "Topical antibiotic if injection points irritated",
    "Acyclovir prophylaxis if history of herpes",
    "Paracetamol 500mg if needed",
  ],
  dashboardWidgets: [
    { id: "sessions_due", labelAr: "الجلسات القادمة", labelEn: "Upcoming sessions" },
    { id: "before_after", labelAr: "صور قبل/بعد", labelEn: "Before/after photos" },
  ],
};
