export const MEDICAL_SPECIALTIES = [
  {
    key: "general_medicine",
    name: "طب عام",
    description: "قوالب للفحص العام، الأعراض الشائعة، والتحويلات.",
    icon: "طع",
    category: "عام",
    map: "قالب زيارة",
    modules: ["فحص عام", "وصفات", "تحويلات"],
  },
  {
    key: "dentistry",
    name: "أسنان",
    description: "قوالب للأسنان، اللثة، الأشعة، وخطة العلاج.",
    icon: "سن",
    category: "الأكثر استخداماً",
    map: "مخطط الأسنان",
    modules: ["خريطة الأسنان", "خطة علاج", "أشعة"],
  },
  {
    key: "gynecology",
    name: "نسائية وتوليد",
    description: "قوالب للحمل، الدورة، السونار، والمتابعة.",
    icon: "ن",
    category: "الأكثر استخداماً",
    map: "خريطة نسائية",
    modules: ["متابعة حمل", "سونار", "زيارات"],
  },
  {
    key: "pediatrics",
    name: "أطفال",
    description: "قوالب للوزن، الطول، الحرارة، والتطعيمات.",
    icon: "ط",
    category: "الأكثر استخداماً",
    map: "خريطة طفل",
    modules: ["نمو", "تطعيمات", "جرعات"],
  },
  {
    key: "dermatology",
    name: "جلدية",
    description: "أمراض الجلد، الآفات، الحكة، الخزعات، والمتابعة.",
    icon: "ج",
    category: "الأكثر استخداماً",
    map: "خريطة الجسم",
    modules: ["آفات جلدية", "صور", "خزعات"],
  },
  {
    key: "aesthetic",
    name: "تجميل",
    description: "بوتوكس، فيلر، ليزر، صور قبل/بعد، وجلسات.",
    icon: "ت",
    category: "الأكثر استخداماً",
    map: "خريطة وجه وجسم",
    modules: ["قبل/بعد", "موافقات", "جلسات"],
  },
  {
    key: "cardiology",
    name: "قلب",
    description: "قوالب للضغط، النبض، ECG، والإيكو.",
    icon: "ق",
    category: "اختصاصات سريرية",
    map: "خريطة قلب",
    modules: ["ضغط", "ECG", "إيكو"],
  },
  {
    key: "ophthalmology",
    name: "عيون",
    description: "قوالب للنظر، الضغط، الفحص، والوصفات.",
    icon: "ع",
    category: "اختصاصات سريرية",
    map: "خريطة العين",
    modules: ["نظر", "ضغط عين", "نظارات"],
  },
  {
    key: "orthopedics",
    name: "عظام",
    description: "قوالب للألم، الحركة، الأشعة، والإجراءات.",
    icon: "ظم",
    category: "اختصاصات سريرية",
    map: "هيكل عظمي",
    modules: ["ألم", "أشعة", "تأهيل"],
  },
  {
    key: "internal_medicine",
    name: "باطنية",
    description: "قوالب للأعراض العامة، الأمراض المزمنة، والتحاليل.",
    icon: "+",
    category: "الأكثر استخداماً",
    map: "خريطة أعضاء",
    modules: ["تحاليل", "أمراض مزمنة", "متابعة"],
  },
  {
    key: "surgery",
    name: "جراحة عامة",
    description: "إجراءات، فحص الجروح، ملاحظات العملية، والمتابعة.",
    icon: "جر",
    category: "إجراءات ومراكز",
    map: "قالب إجراءات",
    modules: ["عملية", "جرح", "متابعة"],
  },
] as const;

export type MedicalSpecialtyKey = (typeof MEDICAL_SPECIALTIES)[number]["key"];

export function isMedicalSpecialty(value: string): value is MedicalSpecialtyKey {
  return MEDICAL_SPECIALTIES.some((specialty) => specialty.key === value);
}
